using Microsoft.EntityFrameworkCore;
using Orchestrix.Logging.Persistence.AzureBlob;
using Orchestrix.Persistence;
using Orchestrix.Locking;
using Orchestrix.ServiceDefaults;
using Orchestrix.Transport;

using Serilog;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddSerilog((services, lc) => lc
    .ReadFrom.Configuration(builder.Configuration)
    .WriteTo.Console());

builder.AddServiceDefaults();


// ...

builder.Services.AddOrchestrixCoordinator(coordinator => 
{
    // coordinator.Options.NodeId = "sample-node-1"; // Auto-generated by default
     coordinator.Locking.UseRedis(options => 
     {
         options.ConnectionString = builder.Configuration.GetConnectionString("redis") ?? "localhost:6379";
     });
     
     coordinator.Transport.UseRedis(builder.Configuration.GetConnectionString("redis") ?? "localhost:6379");
     
     coordinator.Persistence
        .UseEfCore<SampleDbContext>(options =>
        {
             options.UseNpgsql(builder.Configuration.GetConnectionString("orchestrixdb"), b =>
             {
                 b.MigrationsAssembly("Orchestrix.Coordinator.Sample");
             });
        });

     coordinator.Logging
        .UseAzureBlobLogging("UseDevelopmentStorage=true", "orchestrix-logs"); 
});

var host = builder.Build();

// Auto-migration for Sample Project
using (var scope = host.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<SampleDbContext>();
    await context.Database.MigrateAsync();
}

try
{
    host.Run();
}
finally
{
    Log.CloseAndFlush();
}
